In [1]:
%load_ext autoreload
%autoreload 2
%load_ext tensorboard

In [2]:
import pandas as pd
import numpy as np
from pydantic import BaseModel
import sys
import os
from lightning.pytorch.loggers import MLFlowLogger
from loguru import logger
from load_dotenv import load_dotenv
import time
import json
import torch
from torch.utils.data import DataLoader
import lightning as L
from lightning.pytorch.callbacks.early_stopping import EarlyStopping
from lightning.pytorch.callbacks import ModelCheckpoint
import mlflow

sys.path.insert(0, "..")

from src.utils.embedding_id_mapper import IDMapper
from src.algo.gSASRec.model import SASRec
from src.algo.gSASRec.dataset import SASRecDataset
from src.algo.gSASRec.trainer import SASRecLitModule
from src.eval.utils import create_rec_df, create_label_df, merge_recs_with_target
from src.eval.log_metrics import log_ranking_metrics, log_classification_metrics

In [3]:
load_dotenv(override = True)

False

In [ ]:
class Args(BaseModel):
    testing: bool = False
    log_to_mlflow: bool = True
    experiment_name: str = "first-attempt"
    run_name: str = f"018-sasrec"
    notebook_persit_dp: str = None
    
    user_col: str = "user_id"
    item_col: str = "parent_asin"
    rating_col: str = "rating"
    timestamp_col: str = "timestamp"
    group_name: str = "seq-modelling"

    top_K: int = 100
    top_k: int = 10

    batch_size: int = 256
    lr: float = 0.0001
    l2_emb: float = 0.0001
    early_stopping_patience: int = 10
    device: str = "cuda" if torch.cuda.is_available() else "cpu"
    num_epochs: int = 100

    # SASrec specific
    max_len: int = 10
    dropout: float = 0.5
    hidden_units: int = 128
    num_blocks: int = 1
    num_heads: int = 2
    num_workers: int = 4
    gbce_t: int = 0.0
    pad_token: int = 0
    # seq_length: int = 10
    
    train_data_fp: str = os.path.abspath("../data_for_ai/interim/train_sample_interactions_16407u_neg_seq.parquet")
    val_data_fp: str = os.path.abspath("../data_for_ai/interim/val_sample_interactions_16407u_neg_seq.parquet")

    def init(self):
        self.notebook_persit_dp = os.path.abspath(f"data/{self.experiment_name}/{self.run_name}")

        if not (mlflow_uri := os.environ.get("MLFLOW_TRACKING_URI")):
            self.log_to_mlflow = False
            logger.warning("MLFlow is not enabled. Turn off tracking to Mlflow.")

        if self.log_to_mlflow:
            logger.info(
                f"Setting up Mlflow experiment: {self.experiment_name}, run_name: {self.run_name}"
            )

            self._mlf_logger = MLFlowLogger(
                experiment_name=self.experiment_name,
                run_name=self.run_name,
                tracking_uri=mlflow_uri,
                log_model=True,
            )

        if not self.testing:
            os.makedirs(self.notebook_persit_dp, exist_ok=True)
        return self
    
args = Args().init()
print(args.model_dump_json(indent=2))

2025-04-28 10:55:57.501 | WARNING  | __main__:init:43 - MLFlow is not enabled. Turn off tracking to Mlflow.


{
  "testing": false,
  "log_to_mlflow": false,
  "experiment_name": "first-attempt",
  "run_name": "018-sasrec",
  "notebook_persit_dp": "c:\\Users\\Trieu\\OneDrive\\Desktop\\recsys\\real_time_recsys\\notebooks\\data\\first-attempt\\018-sasrec",
  "user_col": "user_id",
  "item_col": "parent_asin",
  "rating_col": "rating",
  "timestamp_col": "timestamp",
  "group_name": "seq-modelling",
  "top_K": 100,
  "top_k": 10,
  "batch_size": 16,
  "lr": 0.0001,
  "l2_emb": 0.0001,
  "early_stopping_patience": 10,
  "device": "cpu",
  "num_epochs": 100,
  "max_len": 10,
  "dropout": 0.5,
  "hidden_units": 128,
  "num_blocks": 1,
  "num_heads": 2,
  "num_workers": 4,
  "gbce_t": 0.0,
  "pad_token": 0,
  "train_data_fp": "c:\\Users\\Trieu\\OneDrive\\Desktop\\recsys\\real_time_recsys\\data_for_ai\\interim\\train_sample_interactions_16407u_neg_seq.parquet",
  "val_data_fp": "c:\\Users\\Trieu\\OneDrive\\Desktop\\recsys\\real_time_recsys\\data_for_ai\\interim\\val_sample_interactions_16407u_neg_seq.

c:\Users\Trieu\AppData\Local\pypoetry\Cache\virtualenvs\hm-scalablerecs-QHnDFvap-py3.11\Lib\site-packages\pydantic\main.py:477: UserWarning:

Pydantic serializer warnings:
  Expected `int` but got `float` with value `0.0` - serialized value may not be as expected



In [5]:
train_df = pd.read_parquet(args.train_data_fp)
# convert train_df["rating"] to 1 if rating > 0 else 0
train_df[args.rating_col] = train_df[args.rating_col].apply(lambda x: 1 if x > 0 else 0)            
# train_df["item_sequence"] = train_df["item_sequence"].apply(lambda x: list(x))

val_df = pd.read_parquet(args.val_data_fp)
# convert val_df["rating"] to 1 if rating > 0 else 0
val_df[args.rating_col] = val_df[args.rating_col].apply(lambda x: 1 if x > 0 else 0)

assert set(val_df[args.user_col].unique()).issubset(set(train_df[args.user_col].unique())), "Validation users must be present in training users."

assert set(val_df[args.item_col].unique()).issubset(set(train_df[args.item_col].unique())), "Validation items must be present in training items."
assert train_df[args.timestamp_col].max() < val_df[args.timestamp_col].min(), "Validation data must be after training data. Otherwise, its a data contamination problem."

In [6]:
val_df

user_id parent_asin  rating  \
0     AGSP5XAQPQBUUXZHEZSC65FD7NOQ  B004FV4ROA       1   
1     AGSP5XAQPQBUUXZHEZSC65FD7NOQ  B07KFQFDNB       0   
2     AEHS7YR7BGGWMZS24H5UR5IP46HQ  B08F1P3BCC       1   
3     AEHS7YR7BGGWMZS24H5UR5IP46HQ  B00HXT8EKE       0   
4     AGAVHCK42EGMVS7DGPRX6HBCUCNQ  B09Q3NR84W       1   
...                            ...         ...     ...   
6953  AEEQZRQBOFHFBFPYBX2BZ5WOI33A  B01A08E70K       0   
6954  AHLN6GKTKZE22AON34YAQXTGK63A  B0C682GZ5X       1   
6955  AHLN6GKTKZE22AON34YAQXTGK63A  B09SWWCN6Q       0   
6956  AEMYBWDN67IB5IBTMHLHN76V4QHQ  B091K4WYD1       1   
6957  AEMYBWDN67IB5IBTMHLHN76V4QHQ  B005CTKYB4       0   

                   timestamp  user_indice  item_indice  \
0    2020-12-27 00:30:31.146        11295          528   
1    2020-12-27 00:30:31.146        11295         3503   
2    2020-12-27 01:44:52.242         1784         3925   
3    2020-12-27 01:44:52.242         1784         1507   
4    2020-12-27 02:25:48.357         9042         4273   
...                      ...          ...          ...   
6953 2022-02-19 16:56:53.030         1396         2441   
6954 2022-02-19 17:28:55.519        14550         4772   
6955 2022-02-19 17:28:55.519        14550         4303   
6956 2022-02-19 22:08:53.253         2446         4086   
6957 2022-02-19 22:08:53.253         2446          654   

                                          item_sequence  
0     [1898, 3479, 3908, 1570, 91, 2723, 2962, 106, ...  
1     [3479, 3908, 1570, 91, 2723, 2962, 106, 3557, ...  
2     [4319, 3382, 4330, 1173, 1330, 423, 2868, 3167...  
3     [3382, 4330, 1173, 1330, 423, 2868, 3167, 1071...  
4     [1311, 1416, 455, 3743, 1823, 2694, 3612, 3462...  
...                                                 ...  
6953  [3451, 3827, 1839, 1347, 2504, 2694, 4546, 427...  
6954  [2950, 1812, 4735, 4165, 4575, 2440, 607, 4807...  
6955  [1812, 4735, 4165, 4575, 2440, 607, 4807, 374,...  
6956  [644, 3602, 4569, 1865, 3030, 3653, 3803, 3998...  
6957  [3602, 4569, 1865, 3030, 3653, 3803, 3998, 285...  

[6958 rows x 7 columns]

In [7]:
train_df.head(3)

user_id parent_asin  rating           timestamp  \
0  AFZ4EK2LJ655XQKTEUELCARO6RYA  B00002EQCW       1 2003-01-23 03:28:15   
1  AFZ4EK2LJ655XQKTEUELCARO6RYA  B095JX15XF       0 2003-01-23 03:28:15   
2  AFY2C4YOUP2SSMM43HD2L3FIEFZA  B00008SCFL       1 2003-11-25 18:12:09   

   user_indice  item_indice                                      item_sequence  
0         8071            4  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  
1         8071         4132  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  
2         7935           36  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....

In [8]:
def init_model(n_user, n_items, dropout, hidden_units, num_blocks, num_heads):
    """
    Initialize the model with the given parameters.
    """
    model = SASRec(
        user_num = n_user,
        item_num = n_items,
        dropout_rate = dropout,
        hidden_units = hidden_units,
        num_blocks = num_blocks,
        num_heads = num_heads,
    )
    return model

In [9]:
batch_size = 2
hidden_units = 8
dropout = 0.2
num_blocks = 1
num_heads = 2

# Mock data
user_indices = [0, 0, 1, 2, 2]
item_indices = [0, 1, 2, 3, 4]
timestamps = [0, 1, 2, 3, 4]
ratings = [0, 4, 5, 3, 0]

user_num = len(set(user_indices))
item_num = len(set(item_indices))

train_test_df = pd.DataFrame(
    {
        "user_indice": user_indices,
        "item_indice": item_indices,
        args.timestamp_col: timestamps,
        args.rating_col: ratings,
    }
)

model = init_model(user_num, item_num, dropout,hidden_units, num_blocks, num_heads)

# Example forward pass
model.eval()
user = torch.tensor([[0]])
seq = torch.tensor([[0,0,0,0,0,1,2,3,4,5]])
target_item = torch.tensor([[2]])
predictions = model.predict(user, seq, target_item)
print(predictions)

tensor([[3.2771e-06]], grad_fn=<SigmoidBackward0>)


In [10]:
print(type(train_df["item_sequence"][0]))


<class 'numpy.ndarray'>


In [11]:
train_df["item_indice"].max() + 1

4817

In [12]:
rating_dataset = SASRecDataset(
    train_df, "user_indice", "item_sequence", "item_indice", "rating",args.max_len, args.pad_token, args.timestamp_col, 
)
val_rating_dataset = SASRecDataset(
    val_df, "user_indice", "item_sequence", "item_indice", "rating", args.max_len, args.pad_token, args.timestamp_col, 
)

train_loader = DataLoader(
    rating_dataset, batch_size=args.batch_size, shuffle=True, drop_last=True
)
val_loader = DataLoader(
    val_rating_dataset, batch_size=args.batch_size, shuffle=False, drop_last=False
)

In [42]:
for i in val_loader:
    print(i["user"])
    print(i["sequence"])
    print(i["item"])
    print(i["rating"])
    break

tensor([11295, 11295,  1784,  1784,  9042,  9042,  1542,  1542, 10418, 10418,
         2786,  2786,  6758,  6758,  8761,  8761])
tensor([[1898, 3479, 3908, 1570,   91, 2723, 2962,  106, 3557, 4172],
        [3479, 3908, 1570,   91, 2723, 2962,  106, 3557, 4172,  528],
        [4319, 3382, 4330, 1173, 1330,  423, 2868, 3167, 1071, 2677],
        [3382, 4330, 1173, 1330,  423, 2868, 3167, 1071, 2677, 3925],
        [1311, 1416,  455, 3743, 1823, 2694, 3612, 3462, 1395, 3793],
        [1416,  455, 3743, 1823, 2694, 3612, 3462, 1395, 3793, 4273],
        [1320, 3089,  341, 2162, 2472,  589, 3710, 2694, 3809, 4253],
        [3089,  341, 2162, 2472,  589, 3710, 2694, 3809, 4253, 3550],
        [4018, 4055, 3714, 2688, 4365, 2850, 4815, 2250, 3886, 1570],
        [4055, 3714, 2688, 4365, 2850, 4815, 2250, 3886, 1570, 4471],
        [4377, 1263, 3698, 4357, 3089, 4590, 4018,  534, 3805, 4615],
        [1263, 3698, 4357, 3089, 4590, 4018,  534, 3805, 4615, 3590],
        [2450, 2228, 2694, 4387

In [13]:
for i in train_loader:
    print(i["user"])
    print(i["sequence"])
    print(i["item"])
    print(i["rating"])
    break

tensor([ 8367, 13692,  2131, 14625, 12421,  2539, 13841,   130, 14364,  3236,
         2478, 14645,  5999,  8945,  1966, 15189])
tensor([[2694,  487, 1000,  631, 3028,  313,  701, 1885,  290,  746],
        [4817, 4817, 4817, 4817,   90, 2513, 2098,   85,    1, 4358],
        [4817,  280, 3585, 4624, 4311, 3927, 4528, 3504, 3743, 4069],
        [4817, 4817, 4817, 4817, 4817, 4817, 4817,  417, 3077, 4582],
        [4817, 3576, 4678, 2250,  660, 1003, 3965, 2076, 4216,  107],
        [3240, 1195, 2521, 1542, 1998, 2648, 3578, 4703, 4004, 3541],
        [4817, 4817, 4817, 4817,  975, 1226,  969, 4211, 4057, 1822],
        [4817, 4817, 4817, 4817, 4817, 2964,  438, 2811,  565, 1408],
        [2516, 4659, 1157,  831,  729, 4623, 3164, 2931, 1418, 3422],
        [4817, 2866, 1329, 2696, 1091, 2660, 2383,  876, 2694, 3461],
        [4817, 4817, 4817, 4817, 4127,  610, 1578,  368,  311, 3811],
        [3678, 2496, 1571, 4220,  354, 2889, 3965, 1481, 4102, 4160],
        [3649,  348, 4130, 4051

In [14]:
item_indices = train_df[args.item_col].unique()
user_indices = train_df[args.user_col].unique()
n_items = len(item_indices)
n_users = len(user_indices)

logger.info(f"Number of users: {n_users}, Number of items: {n_items}")
model = init_model(n_users, n_items, args.dropout, args.hidden_units, args.num_blocks, args.num_heads)

2025-04-28 10:56:02.058 | INFO     | __main__:<module>:6 - Number of users: 16407, Number of items: 4817


In [15]:
model

SASRec(
  (item_emb): Embedding(4819, 128, padding_idx=4818)
  (pos_emb): Embedding(10, 128)
  (emb_dropout): Dropout(p=0.5, inplace=False)
  (attention_layernorms): ModuleList(
    (0): LayerNorm((128,), eps=1e-08, elementwise_affine=True)
  )
  (attention_layers): ModuleList(
    (0): MultiheadAttention(
      (out_proj): NonDynamicallyQuantizableLinear(in_features=128, out_features=128, bias=True)
    )
  )
  (forward_layernorms): ModuleList(
    (0): LayerNorm((128,), eps=1e-08, elementwise_affine=True)
  )
  (forward_layers): ModuleList(
    (0): PointWiseFeedForward(
      (conv1): Conv1d(128, 128, kernel_size=(1,), stride=(1,))
      (dropout1): Dropout(p=0.5, inplace=False)
      (relu): ReLU()
      (conv2): Conv1d(128, 128, kernel_size=(1,), stride=(1,))
      (dropout2): Dropout(p=0.5, inplace=False)
    )
  )
  (final_layer): Linear(in_features=128, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [16]:
idm_path = os.path.abspath("../data_for_ai/interim/idm_16407u.json")
idm = IDMapper().load(idm_path)
idm.get_user_id(1)

'AE227WAM4NWQPJI33OPN7ZARNNZQ'

## overfit 1 batch

In [ ]:
early_stopping = EarlyStopping(
    monitor="val_loss", patience=5, mode="min", verbose=False
)

model = init_model(n_users, n_items, args.dropout, args.hidden_units, args.num_blocks, args.num_heads)
lit_model = SASRecLitModule(
    model,
    log_dir=args.notebook_persit_dp,
    accelerator=args.device,
    lr=args.lr,
    l2_emb=args.l2_emb,
    idm= idm
)

log_dir = f"{args.notebook_persit_dp}/logs/overfit"

# train model
trainer = L.Trainer(
    default_root_dir=log_dir,
    accelerator=args.device if args.device else "auto",
    max_epochs=args.num_epochs,
    overfit_batches=1,
    callbacks=[early_stopping],
)
trainer.fit(
    model=lit_model,
    train_dataloaders=train_loader,
    val_dataloaders=train_loader,
)
logger.info(f"Logs available at {trainer.log_dir}")

You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
`Trainer(overfit_batches=1)` was configured so 1 batch will be used.

  | Name  | Type   | Params | Mode 
-----------------------------------------
0 | model | SASRec | 717 K  | train
-----------------------------------------
717 K     Trainable params
0         Non-trainable params
717 K     Total params
2.871     Total estimated model params size (MB)
20        Modules in train mode
0         Modules in eval mode


Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_epochs=1` reached.
2025-04-28 13:58:30.794 | INFO     | src.algo.gSASRec.trainer:on_fit_end:4 - Logging ranking metrics...

Detected KeyboardInterrupt, attempting graceful shutdown ...


NameError: name 'exit' is not defined

In [ ]:
early_stopping = EarlyStopping(
    monitor="val_loss", patience=args.early_stopping_patience, mode="min", verbose=False, min_delta=0.0025
)

checkpoint_callback = ModelCheckpoint(
    dirpath=f"{args.notebook_persit_dp}/checkpoints",
    filename="best-checkpoint",
    save_top_k=1,
    monitor="val_loss",
    mode="min",
)

model = init_model(n_users, n_items, args.embedding_dim, args.dropout)
lit_model = SASRecLitModule(
    model,
    lr=args.lr,
    l2_emb=args.l2_emb,
    log_dir=args.notebook_persit_dp,
    accelerator=args.device,
    idm= idm
)

log_dir = f"{args.notebook_persit_dp}/logs/run"

# train model
trainer = L.Trainer(
    default_root_dir=log_dir,
    accelerator=args.device if args.device else "auto",
    max_epochs=args.num_epochs,
    callbacks=[early_stopping, checkpoint_callback],
    logger=args._mlf_logger if args.log_to_mlflow else None,
)
trainer.fit(
    model=lit_model,
    train_dataloaders=train_loader,
    val_dataloaders=val_loader,
)

# Change the library as a workaround for the issue in the latest Lightning release
#https://github.com/Lightning-AI/pytorch-lightning/pull/20669/commits/429f732a0528c558e701da7ec01e51c1e2e4f32e

In [ ]:
all_params = [args]

if args.log_to_mlflow:
    run_id = trainer.logger.run_id

    with mlflow.start_run(run_id=run_id):
        for params in all_params:
            params_dict = params.model_dump()
            params_ = dict()
            for k, v in params_dict.items():
                if k == "top_K":
                    k = "top_big_K"
                if k == "top_k":
                    k = "top_small_k"
                params_[f"{params.__repr_name__()}.{k}"] = v
            mlflow.log_params(params_)